[#function getWorkspace]
    [#return "stories"]
[/#function]

[#function getStoryFolder]
    [#return "/stories-demo/"]
[/#function]

[#function getStoryTemplateId]
    [#return "travel-demo-stories-app:pages/story"]
[/#function]

[#function getStoriesLeadTemplateId]
    [#return "travel-demo-stories-app:components/storiesLead"]
[/#function]

[#function getStoriesFolder storiesPage]
    [#assign storiesFolderPath = "/"]
    [#if storiesPage?hasContent]
        [#assign query = "SELECT * FROM [mgnl:component] AS c WHERE ISDESCENDANTNODE('${storiesPage.@path}') AND c.[mgnl:template]='travel-demo-stories-app:components/storiesLead'"]
        [#assign storiesLeadComponents = cmsfn.search("website", query, "JCR-SQL2", "mgnl:component")!]
        [#if storiesLeadComponents?hasContent && cmsfn.asContentMap(storiesLeadComponents[0]).storiesFolder?hasContent]
            [#assign storiesFolderId = cmsfn.asContentMap(storiesLeadComponents[0]).storiesFolder!]
            [#assign storiesFolder = cmsfn.contentById(storiesFolderId, getWorkspace())!]
            [#if storiesFolder?hasContent]
                [#assign storiesFolderPath = storiesFolder.@path!]
            [/#if]
        [/#if]
    [/#if]
    [#return storiesFolderPath]
[/#function]

[#function storyLink currentPage story]
    [#assign rootPageNode = cmsfn.asJCRNode(cmsfn.root(currentPage))!]
    [#assign singleArticlePages = cmsfn.contentListByTemplateId(rootPageNode, getStoryTemplateId())!]
    [#if singleArticlePages?hasContent]
    [#-- We link to the first page we find --]
        [#assign link = cmsfn.link(singleArticlePages?first)!]
        [#assign link = link?removeEnding(".html")]
        [#return link + "~" + story.@name + "~.html"]
    [/#if]
    [#return "#"]
[/#function]

[#function storyBackLink currentPage]
    [#return cmsfn.link(cmsfn.parent(currentPage))]
[/#function]

[#function getAllBlocksOfType blockType]
    [#assign query = "SELECT * FROM [mgnl:block] AS b WHERE ISDESCENDANTNODE('${getStoriesFolder(content)}') AND b.[mgnl:type]='${blockType}'"]
    [#return cmsfn.search(getWorkspace(), query, "JCR-SQL2", "mgnl:block")!]
[/#function]

[#function bookTourLink]
    [#assign bookNode = cmsfn.contentByPath("/travel/book-tour")!]
    [#return cmsfn.link(bookNode)!"#"]
[/#function]

[#function cssBackground image]
    [#assign rendition = damfn.getRendition(image, "original")!]
    [#return rendition?hasContent?then("background-image: url(${rendition.link!}); background-size: cover; background-position: center;", "")]
[/#function]